import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./components/Provider";

const poppin = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <>
        <body className={poppin.className}>
          <Provider>
            {children}
          </Provider>
        </body>
      </>
    </html>
  );
}
